### ISSUE TITLE
Release models on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [Shilin-LU/VINE#1]
Hello @Shilin-LU 🤗 

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work through the daily papers: https://huggingface.co/papers/2410.18775. The paper page lets people discuss about your paper and lets them find artifacts about it (your models for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the checkpoints you've train on https://huggingface.co/models, rather than SharePoint? Hosting on Hugging Face will give you more visibility/enable better discoverability. We can add tags in the model cards so that people find the models easier, link it to the paper page, etc.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

Kind regards,

Niels

**Comment by Shilin-LU** [comment]
Hi Niels,

Thank you for reaching out and for the helpful information!

I’m glad to share that I’ve uploaded my model to Hugging Face as you suggested. You can find it [here](https://huggingface.co/Shilin-LU/VINE-R-Enc). I agree that hosting on Hugging Face offers great visibility and discoverability, and I’m excited for the potential connections this can create within the community.

Thank you again for the guidance!

Best regards,
Shilin

**Comment by NielsRogge** [comment]
Thanks a lot! Great to see the models being linked to the paper, having an image-to-image tag, linked to the dataset, ... etc!

https://huggingface.co/papers/2410.18775 looks great, too!
